include:
  - board: nice_nano_v2
    shield: fifi_left
  - board: nice_nano_v2
    shield: fifi_right
  - board: nice_nano_v2
    shield: urchin_left
  - board: nice_nano_v2
    shield: urchin_right
  - board: corneish_zen_v2_left
  - board: corneish_zen_v2_right
  - board: seeeduino_xiao_ble
    shield: forager_left
  - board: seeeduino_xiao_ble
    shield: forager_right
