include:
  - board: nice_nano_v2
    shield: fifi_left
  - board: nice_nano_v2
    shield: fifi_right
  - board: corneish_zen_v2_left
  - board: corneish_zen_v2_right
  - board: seeeduino_xiao_ble
    shield: forager_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: forager_right rgbled_adapter
