include:
  - board: seeeduino_xiao_ble
    shield: forager_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: forager_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset
