# configuration for https://github.com/caksoylar/keymap-drawer
parse_config:
  raw_binding_map: # convert raw keycode strings to another representation
    '&bootloader': Boot

    '&bt BT_SEL 0': BT 1
    '&bt BT_SEL 1': BT 2
    '&bt BT_SEL 2': BT 3
    '&bt BT_SEL 3': BT 4
    '&bt BT_SEL 4': BT 5

    '&tog_on QWE': QWE On
    '&tog_off QWE': QWE Off

    '&caps_word': Caps Word

    '&mmv MOVE_UP': Mouse ↑
    '&mmv MOVE_DOWN': Mouse ↓
    '&mmv MOVE_LEFT': Mouse ←
    '&mmv MOVE_RIGHT': Mouse →
    '&msc SCRL_UP': Scroll ↑
    '&msc SCRL_DOWN': Scroll ↓
    '&msc SCRL_LEFT': Scroll ←
    '&msc SCRL_RIGHT': Scroll →

    '&mkp LCLK': Left Click
    '&mkp RCLK': Right Click
    '&mkp MB3': Middle Click
    '&mkp MB4': Back Click
    '&mkp MB5': Forward Click

  zmk_combos:
    combo_mouse:  {align: bottom}
    combo_undo:   {align: bottom}
    combo_semi:   {align: bottom}
    combo_capswd: {draw_separate: true}
    combo_caps:   {draw_separate: true}
    combo_ret:    {draw_separate: true}
    combo_lock:   {draw_separate: true}
    combo_bslh:   {draw_separate: true}
    combo_pipe:   {draw_separate: true}

  zmk_keycode_map: # convert keycode to another representation
    # custom mappings
    C_VOL_UP: Vol Up
    C_VOL_DN: Vol Down
    C_PP: Play Pause

    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: Alt
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift
    ESC: Esc
    SPACE: ␣
    BSPC: ⌫
    RET: ⏎
    TAB: ↹
    DEL: ⌦

    PG_UP: Page ↑
    PG_DN: Page ↓
    INS: Insert
    HOME: Home
    END: End
    CAPS: Caps Lock
    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    C_PP: ⏯
    C_NEXT: ⏭️
    C_PREV: ⏮️

    LC(TAB): Tab →
    LC(LS(TAB)): Tab ←
    LC(W): Tab Close
    LC(T): Tab Open
    LC(Z): Undo
    LC(C): Copy
    LC(X): Cut
    LC(V): Paste
    LC(LS(V)): Paste
    LC(Y): Redo
    LG(L): Lock
    LG(R): Rofi

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _

draw_config:
  dark_mode: auto
  separate_combo_diagrams: false
